name: build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - '**/README.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'docs/**'
      - '**/README.md'

jobs:
  call-build-api-workflow:
    uses: .github/workflows/build-api.yml@v1
  
  call-build-android-workflow:
    uses: .github/workflows/build-android.yml@v1
